### PR TITLE
Feature/progressive web app

### PR DESCRIPTION
**Pull request by 14104647ls3**
Changes needed for PWA conversion, however I am experiencing very slow compiling so I need help on verifying the mobile layout.

### CODE REVIEW

**Comment by Pjaijai** [comment]
@14104647ls3  I think you are quite close. Adding  _document may complete this thing. The image thing just let me handle. Many thanks

**Comment by marukosy124** [comment]
Screenshot 2023-11-02 at 12 21 04 AM

 is the manifest actually working? cuz when i run it on localhost it said "no manifest detected"
 
I tried to run [this example nextjs pwa](https://github.com/vercel/next.js/tree/canary/examples/progressive-web-app) and the manifest can be detected

**Comment by 14104647ls3** [comment]
@marukosy124 Yeah it is not working, I am checking on what's wrong.

**Comment by 14104647ls3** [comment]
image
This is the manifest after new commit, we shall see if it can work after @Pjaijai done with the icon.

**Comment by 14104647ls3** [comment]
Ok checked, I put a dummy .png in manifest then can install PWA

**Comment by Pjaijai** [comment]
@14104647ls3 Many thanks ! I will handle the remaining part

**Comment by Pjaijai** [comment]
@14104647ls3  @marukosy124  Updated images and _document file. Please check.

**Review by Pjaijai — APPROVED** [review]
LGTM

**Comment by Pjaijai** [comment]
Need some approval

**Comment by 14104647ls3** [comment]
LGTM as well

**Comment by tommyttf** [comment]
https://nextjs.org/docs/app/building-your-application/configuring/eslint


I believe no need to add `"next/babel"` to `.eslintrc.json`, no that config right now

**Comment by Pjaijai** [comment]
> https://nextjs.org/docs/app/building-your-application/configuring/eslint
> 
> I believe no need to add `"next/babel"` to `.eslintrc.json`, no that config right now

But I found this error if i don't add this
螢幕截圖 2023-11-06 上午12 07 24

**Comment by tommyttf** [comment]
1. in your case, have you re-install the node_modules? `yarn install`

2. `_document.js` (and should be `_document.tsx`) should be placed under `pages/` directory

3. Now `layout.tsx` is overwriting `_document.tsx`, so I guess we just have to merge all things in `_document.tsx` `layout.tsx`.

**Comment by Pjaijai** [comment]
> 1. in your case, have you re-install the node_modules? `yarn install`
> 2. `_document.js` (and should be `_document.tsx`) should be placed under `pages/` directory
> 3. Now `layout.tsx` is overwriting `_document.tsx`, so I guess we just have to merge all things in `_document.tsx` `layout.tsx`.

Right will create PR to fix it

**Comment by tommyttf** [comment]
I will create one now

**Pull request merged**
