### PR TITLE
add global loading placeholder during rendering

### PR DESCRIPTION
**Pull request by ken31ee**
Add a global loading placeholder during rendering.
This is a demo of how to use the nextjs loading ui. Ref: [https://nextjs.org/docs/app/building-your-application/routing/loading-ui-and-streaming](https://nextjs.org/docs/app/building-your-application/routing/loading-ui-and-streaming)
We probably need a better design.

### CODE REVIEW

**Comment by marukosy124** [comment]
@ken31ee I made a [component](https://github.com/Pjaijai/Referalah/blob/development/client/components/layouts/page-status.tsx) for a similar issue before, but I am not a Next.js expert so I probably didn't use the best practice. I think maybe we can combine our codes and create a global component to handle different page status including loading state?

**Comment by ken31ee** [comment]
@marukosy124 We'd better separate the loading and error component. The next.js error and loading fallback leverages the React 18's suspense. Ref: [https://react.dev/reference/react/Suspense](https://react.dev/reference/react/Suspense)

**Comment by marukosy124** [comment]
@ken31ee Great, I'll update my code later then. Thank you

**Comment by marukosy124** [comment]
@ken31ee You're right, I'll update my code later then thankss

**Review by Pjaijai — APPROVED** [review]
LGTM

**Pull request merged**
