### PR TITLE
add frontend setup docs

### PR DESCRIPTION
**Pull request by VardyNg**
I am trying to setup the frontend locally and found that could be nice to have a doc describing how to do that :)

### CODE REVIEW

**Comment by VardyNg** [comment]
The NPM and Node version is sourced from the [package.json](https://github.com/Pjaijai/Referalah/blob/main/client/package.json)

**Comment by Pjaijai** [comment]
Please point to development branch next time

**Review by Pjaijai — APPROVED** [review]
LGTM

**Comment by Pjaijai** [comment]
@VardyNg  I am working on contributor page https://github.com/Pjaijai/Referalah/issues/126. Can you email me the name you want to be displayed, LinkedIn, github or other links.

email: r1r69.referalah@gmail.com

**Comment by VardyNg** [comment]
> @VardyNg I am working on contributor page #126. Can you email me the name you want to be displayed, LinkedIn, github or other links.
> 
> email: [r1r69.referalah@gmail.com](mailto:r1r69.referalah@gmail.com)

Hello, thanks for that, I've send my info to the email :)

**Pull request merged**
