### PR TITLE
Release v1.5.0

### PR DESCRIPTION
**Pull request by Pjaijai**
Major updates:

- Created post detail page
- Created post history page
- Created post edit page
- SEO
- PWA
- using search param instead of setState
- Email (post) will contain user profile link.
- Refactoring

Thank you for all your contributions !!

Will do all tests before deploy

### CODE REVIEW

**Comment by marukosy124** [comment]
@Pjaijai Would you mind listing all the major updates for this version? It would be easier for us to review, thank youuu

**Comment by Pjaijai** [comment]
@marukosy124 sure will do it tonight

**Comment by Pjaijai** [comment]
updated

**Comment by 511234** [comment]
For url search param, better to use `value` instead of `uuid` for country, province, city & industry?

**Comment by Pjaijai** [comment]
> For url search param, better to use `value` instead of `uuid` for country, province, city & industry?

Created issue https://github.com/Pjaijai/Referalah/issues/231

**Review by fishzzzyyy — APPROVED** [review]
All test case passed - tested creating new account, submitting new profile, contacting exisiting job ads & all emails received works.

**Comment by Pjaijai** [comment]
All test cases passed the target release time is 13 Nov 2023 00 am

**Pull request merged**
