### PR TITLE
[Test] Adding Jest set up

### PR DESCRIPTION
**Pull request by VardyNg**
This contains set up of test in unit, integration, and end-2-end test using Jest. 

I think it is best to start set up the test, then adding tests for the missing code. Rather than complete it before merging, for CI purpose.

### CODE REVIEW

**Comment by VardyNg** [comment]
The Test.md is renamed to TEST.md for the sake of convention

**Comment by Pjaijai** [comment]
Can we add react-testing-library ?

**Comment by VardyNg** [comment]
> Can we add react-testing-library ?

Certainly, but I think that will be part of the process of adding test to cover the existing code. I think we can scaffold the testing and allow other test to develop first.

**Review by Pjaijai — APPROVED** [review]
LGTM

**Pull request merged**
