### PR TITLE
add social media url to both email

### PR DESCRIPTION
**Pull request by yaucp**
#99

### CODE REVIEW

**Review by 14104647ls3 — DISMISSED** [review]
Seems ok?

**Comment by Pjaijai** [comment]
Cool will merge after rolling our 1.4.0

**Comment by thomassth** [comment]
It might be easier for everyone to separate linting and formatting from other changes into a separate PR

**Comment by Pjaijai** [comment]
Please do rebase and force push to solve conflic

**Comment by Pjaijai** [comment]
Sloved

**Comment by Pjaijai** [comment]
Closed as outdated. Many Thanks anyway

**Pull request closed without merging**
