### PR TITLE
Doc/update sql script for create user in local 

### PR DESCRIPTION
**Pull request by Pjaijai**
Seems like finding out why the trigger does not successfully migrate so that we need to run the script on local every time. I am thinking any solution to fix this problem. https://github.com/supabase/cli/issues/120

This PR is to update the doc and reply commonly asked question - where can I get the local magic link email

### CODE REVIEW

**Review by ken31ee — APPROVED** [review]

**Comment by 14104647ls3** [comment]
I run again with the local setup procedures
@Pjaijai the magic link from InBucket should redirect to the app to finish the registration process, but currently the magic link redirect user back to InBucket
This is the current link address: http://localhost:54321/auth/v1/verify?token=<token>&type=magiclink&redirect_to=http://localhost:54321
Dev should replace the port in `redirect_to` to 3000

**Comment by Pjaijai** [comment]
> I run again with the local setup procedures @Pjaijai the magic link from InBucket should redirect to the app to finish the registration process, but currently the magic link redirect user back to InBucket This is the current link address: `http://localhost:54321/auth/v1/verify?token=<token>&type=magiclink&redirect_to=http://localhost:54321` Dev should replace the port in `redirect_to` to `3000`

On my end, The url is redirecting to 3000. I am thinking what to I missed in the doc

螢幕截圖 2023-11-10 下午1 29 11

**Comment by Pjaijai** [comment]
@14104647ls3  In comfig.toml , is your site url `site_url = "http://localhost:3000"` ?

**Comment by 14104647ls3** [comment]
> @14104647ls3 In comfig.toml , is your site url `site_url = "http://localhost:3000"` ? and `additional_redirect_urls = ["https://localhost:3000"]`

Yes

**Comment by 14104647ls3** [comment]
@Pjaijai please check the newest commit

**Pull request merged**
