### PR TITLE
Feature/adding testing library

### PR DESCRIPTION
**Pull request by Pjaijai**

### CODE REVIEW

**Comment by marukosy124** [comment]
@Pjaijai Is there anything specific you want to get help with?

**Comment by VardyNg** [comment]
Seems like this branch containing code that doesn't relate to code testing, how about to open another one for this matter?

**Comment by Pjaijai** [comment]
Yes please

**Comment by VardyNg** [comment]
As mentioned in the previous comments, this branch is replaced by https://github.com/Pjaijai/Referalah/tree/test/setup

**Pull request closed without merging**
