### PR TITLE
search url using value instead of uuid

### PR DESCRIPTION
**Pull request by trevorwongtw**

### CODE REVIEW

**Comment by Pjaijai** [comment]
Many thanks. Do you mind doing the same thing to useSearchReferral hook ?

**Comment by trevorwongtw** [comment]
thanks for the review. sure, no problem

**Comment by Pjaijai** [comment]
Rebased and fixed file conflict

**Comment by Pjaijai** [comment]
New commits fixed flowing issue
1. Making city search with value instead of uuid
2. Clicking reset button should reset the parmas
3. Adding a hook to set the initial search value
4. Adding a boolean check that prevent several duplicated api (post + referrals) calls. It only call after locations apis are ready

**Pull request merged**
