### PR TITLE
Should throw error after catching it

### PR DESCRIPTION
**Pull request by Pjaijai**

### CODE REVIEW

**Comment by tommyttf** [comment]
It you throw it eventually without any handling in the catch block, then no need to catch it at the first place

**Comment by Pjaijai** [comment]
@tommyttf  We do have some error handling in api hooks. If we don't throw error, the hooks will not run onError.

**Comment by tommyttf** [comment]
I mean
```
  createPost: async (req: ICreatePostRequest) => {
    try {
      await supabase.from("post").insert({
        url: req.url,
        country_uuid: req.countryUuid,
        province_uuid: req.provinceUuid,
        city_uuid: req.cityUuid,
        industry_uuid: req.industryUuid,
        year_of_experience: req.yearOfExperience,
        created_by: req.createdBy,
        type: req.type,
        company_name: req.companyName.trim(),
        job_title: req.jobTitle.trim(),
        description: req.description.trim(),
      })
    } catch (error) {
      throw error
    }
  },
  ```
  is the same as
  ```
  createPost: async (req: ICreatePostRequest) => {
      await supabase.from("post").insert({
        url: req.url,
        country_uuid: req.countryUuid,
        province_uuid: req.provinceUuid,
        city_uuid: req.cityUuid,
        industry_uuid: req.industryUuid,
        year_of_experience: req.yearOfExperience,
        created_by: req.createdBy,
        type: req.type,
        company_name: req.companyName.trim(),
        job_title: req.jobTitle.trim(),
        description: req.description.trim(),
      })
  },
  ```

**Comment by Pjaijai** [comment]
Right will do some refactoring later.

**Pull request merged**
