### PR TITLE
 [Issue #226] Bugfix/post-card-ui

### PR DESCRIPTION
**Pull request by marukosy124**

### CODE REVIEW

**Comment by 511234** [comment]
The UI changes LGTM.

See if can also fix nested `<a> `issue for `post-history.tsx` at Line 71 & `info-display/header.tsx` at Line 33.
Maybe change to onClick and do e.preventDefault()?

Browser warning:
```
validateDOMNesting(...): <a> cannot appear as a descendant of <a>.
```

**Comment by marukosy124** [comment]
@511234 Fixed, please check. Thank you.

**Review by 511234 — APPROVED** [review]
lgtm thanks:)

**Review by Pjaijai — APPROVED** [review]
LGTM

**Pull request merged**
