### PR TITLE
[#131] adding husky

### PR DESCRIPTION
**Pull request by tommyttf**
Added husky and lint-staged

please check if the pre-commit hook works
`client/lint-staged.config.js`

I am using my macbook and it works

can try by adding lots of spaces, new lines in any files and then commit
should block you from commit as no changes after all

### CODE REVIEW

**Comment by tommyttf** [comment]
need to run `yarn install` at root folder and `client`

if ok then add some instructions in the DEVELOPER.md

**Comment by 511234** [comment]
When husky runs, it runs `yarn tsc --noEmit` from `lint-staged.config.js`
It updates `tsconfig.tsbuildinfo` every time after a commit is made.
The file is not useful for development as it only enhances build compilation.
It's troublesome to rollback the changes there.

According to [this discussion on Next.js github](https://github.com/vercel/next.js/discussions/30815), maybe we could just add `tsconfig.tsbuildinfo` to .gitignore. (and run `git rm --cached tsconfig.tsbuildinfo`)

Otherwise, second approach is to change `yarn tsc --noEmit` to `yarn tsc --noEmit --incremental false`

**Comment by tommyttf** [comment]
@pauljaijai see if anything goes well
may also consider what rules needed to be added to eslint and prettier

**Comment by Pjaijai** [comment]
Fixed file conflict

**Comment by Pjaijai** [comment]
@tommyttf @511234  Hi ! It work on my side and I added `tsconfig.tsbuildinfo` to `.gitignore` please check

**Pull request merged**
