### PR TITLE
Feature/seo optimization

### PR DESCRIPTION
**Pull request by 511234**
Ref: https://github.com/Pjaijai/Referalah/issues/164

- Move jsx elements in [userUuid].tsx to `module/profile/template.tsx` to separate client & server side rendering
- Add metadata (see table at issue #164 )
- Use `robots: noindex,nofollow` on private policy page & terms and condition page

Misc:
- Immediately prompt user to 404 template on `[userUuid].tsx` if param is null

### CODE REVIEW

**Comment by Pjaijai** [comment]
Please add yourself into contributor page

**Comment by 511234** [comment]
https://github.com/Pjaijai/Referalah/pull/212/commits/a3c0e7a890f8e9ae8ff7c24ffd67027bdd498129: Added spacing to avoid user unintentionally clicking on wrong elements  

Before:
Screenshot 2023-11-06 at 11 14 28

After:
Screenshot 2023-11-06 at 11 16 31

**Comment by 511234** [comment]
https://github.com/Pjaijai/Referalah/pull/212/commits/2d41c5e2dea137b8764649c6a942df94c50c725c: Add `aria-label` to improve accessibility score

Before:
Screenshot 2023-11-06 at 11 27 08

After:
Screenshot 2023-11-06 at 11 27 38

**Comment by 511234** [comment]
> Please add yourself into contributor page

Added, please check

**Comment by Pjaijai** [comment]
I fixed some typos and adding some keywords please check

**Review by Pjaijai — APPROVED** [review]
LGTM Many Thanks

**Comment by 511234** [comment]
great, thanks!

**Comment by 511234** [comment]
See if later we can change [userUuid].tsx to meaningful url, like [username].tsx

**Pull request merged**
